# Generated by Django 5.2.1 on 2025-05-14 08:52

from django.db import migrations
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            """
            DROP TABLE IF EXISTS workspace_filenode CASCADE;
            DROP TABLE IF EXISTS workspace_fileversion CASCADE;
            DROP TABLE IF EXISTS workspace_filecomment CASCADE;
            DROP TABLE IF EXISTS workspace_wikiarticle CASCADE;
            DROP TABLE IF EXISTS workspace_projectdashboard CASCADE;
            DROP TABLE IF EXISTS workspace_pdfdocument CASCADE;
            """,
            reverse_sql=migrations.RunSQL.noop
        ),
    ]
