# Generated by Django 5.2.1 on 2025-05-15 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('files', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='directory',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='directory',
            name='is_sidebar_item',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='directory',
            name='type',
            field=models.CharField(default='folder', max_length=20),
        ),
        migrations.AlterField(
            model_name='directory',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_directories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='directory',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='directories', to='core.project'),
        ),
        migrations.AlterUniqueTogether(
            name='directory',
            unique_together={('name', 'project', 'parent', 'is_sidebar_item')},
        ),
    ]
