# Generated by Django 5.2.1 on 2025-05-15 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_alter_directory_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='directory',
            name='has_page',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='directory',
            name='page_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='directory',
            name='page_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='directory',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='file',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
