# Generated by Django 5.2.1 on 2025-05-21 21:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
        ('files', '0003_directory_has_page_directory_page_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
                ('page_number', models.IntegerField()),
                ('comment', models.TextField()),
                ('color', models.CharField(default='#FFEB3B', max_length=20)),
                ('status', models.CharField(choices=[('new_comment', 'Ny kommentar'), ('action_required', 'Kräver åtgärd'), ('rejected', 'Avvisad'), ('new_review', 'Ny granskning'), ('other_forum', 'Annat forum'), ('resolved', 'Åtgärdad')], default='new_comment', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_pdf_annotations', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_annotations', to=settings.AUTH_USER_MODEL)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='files.file')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_annotations', to='core.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
